try:
    from phantom.cef import CEF_JSON, CEF_NAME_MAPPING

    _soar_is_available = True
except ImportError:
    _soar_is_available = False

from typing import TYPE_CHECKING

if TYPE_CHECKING or not _soar_is_available:
    CEF_NAME_MAPPING = {
        "act": "deviceAction",
        "app": "applicationProtocol",
        "applicationProtocol": "app",
        "baseEventCount": "cnt",
        "bytesIn": "in",
        "bytesOut": "out",
        "cat": "deviceEventCategory",
        "cn1": "deviceCustomNumber1",
        "cn1Label": "deviceCustomNumber1Label",
        "cn2": "deviceCustomNumber2",
        "cn2Label": "deviceCustomNumber2Label",
        "cn3": "deviceCustomNumber3",
        "cn3Label": "deviceCustomNumber3Label",
        "cnt": "baseEventCount",
        "cs1": "deviceCustomString1",
        "cs1Label": "deviceCustomString1Label",
        "cs2": "deviceCustomString2",
        "cs2Label": "deviceCustomString2Label",
        "cs3": "deviceCustomString3",
        "cs3Label": "deviceCustomString3Label",
        "cs4": "deviceCustomString4",
        "cs4Label": "deviceCustomString4Label",
        "cs5": "deviceCustomString5",
        "cs5Label": "deviceCustomString5Label",
        "cs6": "deviceCustomString6",
        "cs6Label": "deviceCustomString6Label",
        "destinationAddress": "dst",
        "destinationDnsDomain": "destinationDnsDomain",
        "destinationHostName": "dhost",
        "destinationMacAddress": "dmac",
        "destinationNtDomain": "dntdom",
        "destinationPort": "dpt",
        "destinationProcessName": "dproc",
        "destinationServiceName": "destinationServiceName",
        "destinationTranslatedAddress": "destinationTranslatedAddress",
        "destinationTranslatedPort": "destinationTranslatedPort",
        "destinationUserId": "duid",
        "destinationUserName": "duser",
        "destinationUserPrivileges": "dpriv",
        "deviceAction": "act",
        "deviceAddress": "dvc",
        "deviceCustomDate1": "deviceCustomDate1",
        "deviceCustomDate1Label": "deviceCustomDate1Label",
        "deviceCustomDate2": "deviceCustomDate2",
        "deviceCustomDate2Label": "deviceCustomDate2Label",
        "deviceCustomNumber1": "cn1",
        "deviceCustomNumber1Label": "cn1Label",
        "deviceCustomNumber2": "cn2",
        "deviceCustomNumber2Label": "cn2Label",
        "deviceCustomNumber3": "cn3",
        "deviceCustomNumber3Label": "cn3Label",
        "deviceCustomString1": "cs1",
        "deviceCustomString1Label": "cs1Label",
        "deviceCustomString2": "cs2",
        "deviceCustomString2Label": "cs2Label",
        "deviceCustomString3": "cs3",
        "deviceCustomString3Label": "cs3Label",
        "deviceCustomString4": "cs4",
        "deviceCustomString4Label": "cs4Label",
        "deviceCustomString5": "cs5",
        "deviceCustomString5Label": "cs5Label",
        "deviceCustomString6": "cs6",
        "deviceCustomString6Label": "cs6Label",
        "deviceDirection": "deviceDirection",
        "deviceDnsDomain": "deviceDnsDomain",
        "deviceEventCategory": "cat",
        "deviceExternalId": "deviceExternalId",
        "deviceFacility": "deviceFacility",
        "deviceHostname": "dvchost",
        "deviceInboundInterface": "deviceInboundInterface",
        "deviceMacAddress": "deviceMacAddress",
        "deviceOutboundInterface": "deviceOutboundInterface",
        "deviceProcessName": "deviceProcessName",
        "deviceTranslatedAddress": "deviceTranslatedAddress",
        "dhost": "destinationHostName",
        "dmac": "destinationMacAddress",
        "dntdom": "destinationNtDomain",
        "dpriv": "destinationUserPrivileges",
        "dproc": "destinationProcessName",
        "dpt": "destinationPort",
        "dst": "destinationAddress",
        "duid": "destinationUserId",
        "duser": "destinationUserName",
        "dvc": "deviceAddress",
        "dvchost": "deviceHostname",
        "end": "endTime",
        "endTime": "end",
        "externalId": "externalId",
        "eventOutcome": "outcome",
        "fileCreateTime": "fileCreateTime",
        "fileHash": "fileHash",
        "fileHashMd5": "fileHashMd5",
        "fileHashSha1": "fileHashSha1",
        "fileHashSha256": "fileHashSha256",
        "fileHashSha512": "fileHashSha512",
        "fileId": "fileId",
        "fileModificationTime": "fileModificationTime",
        "fileName": "fileName",
        "filePath": "filePath",
        "filePermission": "filePermission",
        "fileSize": "fSize",
        "fileType": "fileType",
        "fname": "fileName",
        "fsize": "fileSize",
        "in": "bytesIn",
        "message": "msg",
        "msg": "message",
        "oldfileCreateTime": "oldfileCreateTime",
        "oldfileHash": "oldfileHash",
        "oldfileId": "oldfileId",
        "oldfileModificationTime": "oldfileModificationTime",
        "oldfileName": "oldfileName",
        "oldfilePath": "oldfilePath",
        "oldfilePermission": "oldfilePermission",
        "oldfileType": "oldfileType",
        "oldfsize": "oldfsize",
        "out": "bytesOut",
        "outcome": "eventOutcome",
        "proto": "transportProtocol",
        "receiptTime": "rt",
        "request": "requestURL",
        "requestClientApplication": "requestClientApplication",
        "requestCookies": "requestCookies",
        "requestMethod": "requestMethod",
        "requestURL": "request",
        "rt": "receiptTime",
        "shost": "sourceHostName",
        "smac": "sourceMacAddress",
        "sntdom": "sourceNtDomain",
        "sourceAddress": "src",
        "sourceDnsDomain": "sourceDnsDomain",
        "sourceHostName": "shost",
        "sourceMacAddress": "smac",
        "sourceNtDomain": "sntdom",
        "sourcePort": "spt",
        "sourceServiceName": "sourceServiceName",
        "sourceTranslatedAddress": "sourceTranslatedAddress",
        "sourceTranslatedPort": "sourceTranslatedPort",
        "sourceUserId": "suid",
        "sourceUserName": "suser",
        "sourceUserPrivileges": "spriv",
        "spriv": "sourceUserPrivileges",
        "spt": "sourcePort",
        "src": "sourceAddress",
        "start": "startTime",
        "startTime": "start",
        "suid": "sourceUserId",
        "suser": "sourceUserName",
        "transportProtocol": "proto",
    }

    CEF_JSON = {
        "act": {"contains": []},
        "app": {"contains": []},
        "applicationProtocol": {"contains": []},
        "baseEventCount": {"contains": []},
        "bytesIn": {"contains": []},
        "bytesOut": {"contains": []},
        "cat": {"contains": []},
        "cn1": {"contains": []},
        "cn1Label": {"contains": []},
        "cn2": {"contains": []},
        "cn2Label": {"contains": []},
        "cn3": {"contains": []},
        "cn3Label": {"contains": []},
        "cnt": {"contains": []},
        "cs1": {"contains": []},
        "cs1Label": {"contains": []},
        "cs2": {"contains": []},
        "cs2Label": {"contains": []},
        "cs3": {"contains": []},
        "cs3Label": {"contains": []},
        "cs4": {"contains": []},
        "cs4Label": {"contains": []},
        "cs5": {"contains": []},
        "cs5Label": {"contains": []},
        "cs6": {"contains": []},
        "cs6Label": {"contains": []},
        "destinationAddress": {"contains": ["ip"]},
        "destinationDnsDomain": {"contains": ["domain"]},
        "destinationHostName": {"contains": ["host name"]},
        "destinationMacAddress": {"contains": ["mac address"]},
        "destinationNtDomain": {"contains": []},
        "destinationPort": {"contains": ["port"]},
        "destinationProcessName": {"contains": ["process name"]},
        "destinationServiceName": {"contains": ["process name"]},
        "destinationTranslatedAddress": {"contains": ["ip"]},
        "destinationTranslatedPort": {"contains": ["port"]},
        "destinationUserId": {"contains": []},
        "destinationUserName": {"contains": ["user name"]},
        "destinationUserPrivileges": {"contains": []},
        "deviceAction": {"contains": []},
        "deviceAddress": {"contains": ["ip"]},
        "deviceCustomDate1": {"contains": []},
        "deviceCustomDate1Label": {"contains": []},
        "deviceCustomDate2": {"contains": []},
        "deviceCustomDate2Label": {"contains": []},
        "deviceCustomNumber1": {"contains": []},
        "deviceCustomNumber1Label": {"contains": []},
        "deviceCustomNumber2": {"contains": []},
        "deviceCustomNumber2Label": {"contains": []},
        "deviceCustomNumber3": {"contains": []},
        "deviceCustomNumber3Label": {"contains": []},
        "deviceCustomString1": {"contains": []},
        "deviceCustomString1Label": {"contains": []},
        "deviceCustomString2": {"contains": []},
        "deviceCustomString2Label": {"contains": []},
        "deviceCustomString3": {"contains": []},
        "deviceCustomString3Label": {"contains": []},
        "deviceCustomString4": {"contains": []},
        "deviceCustomString4Label": {"contains": []},
        "deviceCustomString5": {"contains": []},
        "deviceCustomString5Label": {"contains": []},
        "deviceCustomString6": {"contains": []},
        "deviceCustomString6Label": {"contains": []},
        "deviceDirection": {"contains": []},
        "deviceDnsDomain": {"contains": ["domain"]},
        "deviceEventCategory": {"contains": []},
        "deviceExternalId": {"contains": []},
        "deviceFacility": {"contains": []},
        "deviceHostname": {"contains": ["host name"]},
        "deviceInboundInterface": {"contains": []},
        "deviceMacAddress": {"contains": ["mac address"]},
        "deviceOutboundInterface": {"contains": []},
        "deviceProcessName": {"contains": ["process name"]},
        "deviceTranslatedAddress": {"contains": ["ip"]},
        "dhost": {"contains": ["host name"]},
        "dmac": {"contains": ["mac address"]},
        "dntdom": {"contains": ["domain"]},
        "dpriv": {"contains": []},
        "dproc": {"contains": ["process name"]},
        "dpt": {"contains": ["port"]},
        "dst": {"contains": ["ip"]},
        "duid": {"contains": []},
        "duser": {"contains": ["user name"]},
        "dvc": {"contains": ["ip"]},
        "dvchost": {"contains": ["host name"]},
        "end": {"contains": []},
        "endTime": {"contains": []},
        "externalId": {"contains": []},
        "eventOutcome": {"contains": []},
        "fileCreateTime": {"contains": []},
        "fileHash": {"contains": ["hash"]},
        "fileHashMd5": {"contains": ["md5"]},
        "fileHashSha1": {"contains": ["sha1"]},
        "fileHashSha256": {"contains": ["sha256"]},
        "fileHashSha512": {"contains": ["sha512"]},
        "fileId": {"contains": []},
        "fileModificationTime": {"contains": []},
        "fileName": {"contains": ["file name"]},
        "filePath": {"contains": ["file path"]},
        "filePermission": {"contains": []},
        "fileSize": {"contains": []},
        "fileType": {"contains": []},
        "fname": {"contains": ["file name"]},
        "fsize": {"contains": []},
        "in": {"contains": []},
        "message": {"contains": []},
        "msg": {"contains": []},
        "oldfileCreateTime": {"contains": []},
        "oldfileHash": {"contains": ["hash"]},
        "oldfileId": {"contains": []},
        "oldfileModificationTime": {"contains": []},
        "oldfileName": {"contains": ["file name"]},
        "oldfilePath": {"contains": ["file path"]},
        "oldfilePermission": {"contains": []},
        "oldfileType": {"contains": []},
        "oldfsize": {"contains": []},
        "out": {"contains": []},
        "outcome": {"contains": []},
        "proto": {"contains": []},
        "receiptTime": {"contains": []},
        "request": {"contains": []},
        "requestClientApplication": {"contains": []},
        "requestCookies": {"contains": []},
        "requestMethod": {"contains": []},
        "requestURL": {"contains": ["url"]},
        "rt": {"contains": []},
        "shost": {"contains": ["host name"]},
        "smac": {"contains": ["mac address"]},
        "sntdom": {"contains": ["domain"]},
        "sourceAddress": {"contains": ["ip"]},
        "sourceDnsDomain": {"contains": ["domain"]},
        "sourceHostName": {"contains": ["host name"]},
        "sourceMacAddress": {"contains": ["mac address"]},
        "sourceNtDomain": {"contains": []},
        "sourcePort": {"contains": ["port"]},
        "sourceServiceName": {"contains": []},
        "sourceTranslatedAddress": {"contains": ["ip"]},
        "sourceTranslatedPort": {"contains": ["port"]},
        "sourceUserId": {"contains": []},
        "sourceUserName": {"contains": ["user name"]},
        "sourceUserPrivileges": {"contains": []},
        "spriv": {"contains": []},
        "spt": {"contains": ["port"]},
        "src": {"contains": ["ip"]},
        "start": {"contains": []},
        "startTime": {"contains": []},
        "suid": {"contains": []},
        "suser": {"contains": ["user name"]},
        "transportProtocol": {"contains": []},
        "vaultId": {"contains": ["vault id"]},
    }

__all__ = ["CEF_JSON", "CEF_NAME_MAPPING"]
