name: PR Checks
on:
  push:
    branches:
      - main
      - beta
  pull_request:

jobs:
  Precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      - name: Install pre-commit
        run: uv tool install pre-commit --with pre-commit-uv
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-cache

  MyPy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: MyPy - ${{ matrix.python-version }}
        run: uv run --locked mypy .

  Pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Pytest + Coverage - ${{ matrix.python-version }}
        run: uv run --locked pytest -n auto

  Generate_Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      - name: Install dependencies with docs extras
        run: uv sync --group docs
      - name: Build documentation with Sphinx
        run: |
          cd docs
          uv run sphinx-build -b html . _build/html
          # Create .nojekyll file to allow files starting with underscore
          touch _build/html/.nojekyll
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html
          retention-days: 7

  Publish_Docs:
    runs-on: ubuntu-latest
    needs: Generate_Docs
    if: success()
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: ${{ github.ref_name == 'main' && 'github-pages' || 'github-pages-testing' }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Debug branch info
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"

      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/_build/html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          enablement: true
